- hosts: all
  become: yes
  tasks:
    - name: "Basic setup"
      import_tasks: ./tasks/install-basic.yml
      tags: 
        - basic_setup

    - name: "Setup Mongodb"
      import_role:
         name: "../../roles/mongodb_replica"
      tags: 
        - mongodb

    - name: "Setup Node Exporter"
      import_tasks: ./tasks/node-exporter.yml
      tags: 
        - node_exporter
