---
all:
  vars:
    ansible_user: ubuntu
    node_exporter_version: 1.1.2
    ruby: present
    basic_packages:
      - name: tmux
        state: present
      - name: htop
        state: present
      - name: s3fs
        state: present

  children:
    master:
      hosts:
        mongo-rs-01:
          ansible_host: ""
    replica:
      hosts:
        mongo-rs-02:
          ansible_host: ""
        mongo-rs-03:
          ansible_host: ""
